service: sf-api-gateway

provider:
  name: aws
  region: ${self:custom.${self:provider.stage}.region}
  runtime: go1.x
  memorySize: 192
  stage: ${opt:stage, 'dev'}
  environment:
    AUTH_SECRET: ${ssm:/${self:service}/${self:provider.stage}/authSecret~true}

package:
  exclude:
  - ./**
  include:
  - ./bin/**

functions:
  JwtAuthorizer:
    handler: bin/handlers/JwtAuthorizer

  Healthcheck:
    handler: bin/handlers/Healthcheck
    events:
      - http:
          path: healthcheck
          method: get

  Restricted:
    handler: bin/handlers/Restricted
    events:
      - http:
          path: restricted
          method: get
          authorizer:
            name: JwtAuthorizer
            resultTtlInSeconds: 0

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: ${self:custom.${self:provider.stage}.domain}
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
  dev:
    domain: "api-dev.stockfile.ph"
    region: "ap-southeast-2" # Sydney
  staging:
    domain: "api-staging.stockfile.ph"
    region: "ap-southeast-1" # Singapore
  prod:
    domain: "api.stockfile.ph"
    region: "ap-southeast-1" # Singapore
